version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  php:
    build: .
    volumes:
      - ./:/var/www/html
      - ./docker-mysql.ini:/var/www/private/db_config.ini

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-d34fAu1t}
      MYSQL_USER: db_user
      MYSQL_PASSWORD: p4ssW0rd
      MYSQL_DATABASE: db_name
    volumes:
      - db:/var/lib/mysql
      - ./config/splitlist.sql:/docker-entrypoint-initdb.d/splitlist.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      PMA_HOST:
      PMA_USER: db_user
      PMA_PASSWORD: p4ssW0rd

volumes:
  db:
